### ISSUE TITLE
Sonos disappears after few minutes

### ISSUE THREAD

**Issue by Dudiello** [philippe44/AirConnect#38]
Airupnp on BSD, Sonos is correctly found and works perfectly with Youtube app from iOS.

After few minutes, Sonos disappears from the list of devices on iOS. 

Launching airupnp with all=sdebug reports nothing particular. 

This is repeatable and happens after 3-5 minutes from airupnp launch.

(version 1.6.1)

**Comment by philippe44** [comment]
Please try version 0.2.0.0 which has totally changed the detection logic. Hopefully, other issues that I've added with this version, player disappearing problem should be fixed

**Comment by Dudiello** [comment]
Thanks Philippe, I tried 2.0.1 and the problem persists. Let me know if I can help in any way for detecting the issue (e.g. send you the log file, although nothing special appears)

**Comment by Dudiello** [comment]
Hi,

I also tried 2.0.2 on OS X. Same behavior, after few minutes Sonos disappears from the list of Airplay devices and sound stop.

**Comment by philippe44** [comment]
Can you post here a log?

**Comment by oerik** [comment]
I have noticed the same on my system.  It appears that the timeout is too low, my sonos (I have 6 of them) advertise every 5 minutes according to the log.  See these logging extracts.

I think you need to change the code at airupnp/src/airupnp.c:48:
```
--- airupnp.c	2018-02-04 17:25:56.233849430 +0100
+++ airupnp.new.c	2018-02-05 18:55:34.509474712 +0100
@@ -46,7 +46,7 @@
 #define GROUP_RENDERING_CTRL	"urn:schemas-upnp-org:service:GroupRenderingControl"
 
 #define DISCOVERY_TIME 		20
-#define PRESENCE_TIMEOUT	(DISCOVERY_TIME * 6)
+#define PRESENCE_TIMEOUT	(DISCOVERY_TIME * 15)

```

Logging:
```
[18:40:17.500257] AddMRDevice:874 [0x697a40]: adding renderer (Scharrel)
[18:40:17.500370] AddMRDevice:888 [0x697a40]: cannot get mac Scharrel+, creating fake 92e5692a
[18:40:17.548247] MasterHandler:574 [0x697a40]: subscribe success
<removed some logging>
[18:42:25.002717] UpdateThread:640 [0x697a40]: removing unresponsive player (Scharrel+)
[18:45:17.329903] AddMRDevice:874 [0x697a40]: adding renderer (Scharrel)
[18:45:17.330005] AddMRDevice:888 [0x697a40]: cannot get mac Scharrel+, creating fake 92e5692a
[18:45:17.364236] MasterHandler:574 [0x697a40]: subscribe success

```

**Comment by philippe44** [comment]
That's strange b/c I do not rely on their advertising, it's too inconsistent in UPnP. I do search every 30s

**Comment by oerik** [comment]
Well, it turned out that I did not have multicast enabled on my home network. However, the advertising looks pretty solid every 5 minutes.

**Comment by philippe44** [comment]
Good - @Dudiello, can you check this is not an issue with your network

**Comment by Dudiello** [comment]
Hi Philippe, will check this on the weekend for sure.

Question: if it is a Multicast issue, shouldn't the device be discovered at all rather than appear and then disappear?

**Comment by philippe44** [comment]
that's a good question for which I don't have the answer ...

**Comment by persi-persu** [comment]
I have basically the same problem. My router is an Asus RT-AC68U.

**Comment by Dudiello** [comment]
Hi,

I did lot of debug activities on my firewall and everything is fine on that side.

Even with 2.0.4 same issues happens, after a random of numbers of minutes, Sonos disappears from the list of availalbe devices on iOS.

Here is the debud (-d all=debug)

[18:38:34.826098] main:1189 Starting airupnp version: v0.2.0.4 (Feb 19 2018 @ 02:11:24)
[18:38:34.826739] main:1197 no config file, using defaults
[18:38:34.829747] Start:949 Binding to 192.168.2.104:49152
[18:38:35.031973] AddMRDevice:865 [0x6a1aa0]: adding renderer (Cucina)
[18:38:35.032043] SendARP:475 No SendARP build for this platform
[18:38:35.032059] AddMRDevice:879 [0x6a1aa0]: cannot get mac Cucina+, creating fake 804a082c
[18:38:35.051099] MasterHandler:580 [0x6a1aa0]: subscribe success
[18:38:35.070671] ProcessEvent:385 [0x6a1aa0]: UPnP Volume local change 44
[18:38:35.228870] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:38:38.226257] AddMRDevice:865 [0x6a3608]: adding renderer ([TV]UE55D6500)
[18:38:38.226307] SendARP:475 No SendARP build for this platform
[18:38:38.226322] AddMRDevice:879 [0x6a3608]: cannot get mac [TV]UE55D6500+, creating fake f54373df
[18:38:38.228368] MasterHandler:580 [0x6a3608]: subscribe success
[18:38:39.213352] ProcessEvent:385 [0x6a3608]: UPnP Volume local change 8
[18:38:47.210659] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:38:54.000855] UpdateThread:636 Presence checking
[18:38:54.210107] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:38:54.615294] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:38:54.721747] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:39:09.208515] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:39:14.003497] UpdateThread:636 Presence checking
[18:39:14.208075] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:39:14.563025] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:39:14.594432] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:39:21.208000] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:39:34.002937] UpdateThread:636 Presence checking
[18:39:34.164114] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:39:34.356007] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:39:37.205930] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:39:50.204716] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:39:54.027487] UpdateThread:636 Presence checking
[18:39:54.257241] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:39:54.675328] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:40:00.203756] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:40:12.202708] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:40:14.005088] UpdateThread:636 Presence checking
[18:40:14.705956] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:40:15.057942] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:40:25.201578] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:40:30.201344] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:40:34.016944] UpdateThread:636 Presence checking
[18:40:34.200758] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:40:34.576396] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:40:34.858080] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:40:49.199226] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:40:54.010227] UpdateThread:636 Presence checking
[18:40:54.413595] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:40:54.547938] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:40:55.198984] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:40:58.198603] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:41:14.018156] UpdateThread:636 Presence checking
[18:41:14.224873] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:41:14.322430] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:41:19.196525] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:41:27.195897] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:41:34.014656] UpdateThread:636 Presence checking
[18:41:34.195272] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:41:34.360890] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:41:34.652925] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:41:50.194550] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:41:54.009032] UpdateThread:636 Presence checking
[18:41:54.452134] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:41:54.594745] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:42:03.192452] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:42:07.192211] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:42:14.023930] UpdateThread:636 Presence checking
[18:42:14.191429] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:42:14.789810] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:42:14.830531] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:42:23.190565] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:42:34.003567] UpdateThread:636 Presence checking
[18:42:34.508728] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:42:34.650856] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[18:42:44.188462] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:42:51.187893] UpdateThread:693 [0x6a3608] UPnP keep alive: [TV]UE55D6500+
[18:42:54.025413] UpdateThread:636 Presence checking
[18:42:54.790804] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+


nothing specific to call out

**Comment by philippe44** [comment]
There has to be, in the log, something that shows when the player disappear

**Comment by Dudiello** [comment]
Hi have a SonicWALL and I did all the packet inspections and nothing gets dropped....any way I can increase verbosity of the log?

**Comment by Dudiello** [comment]
Did some other tests today, here is the last part of log (all=sdebug)

[11:00:04.729503] MasterHandler:497 event: 6 [UPNP_DISCOVERY_SEARCH_RESULT] [0x0] (recurse 0)
[11:00:04.741299] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[11:00:24.015263] MasterHandler:497 event: 7 [UPNP_DISCOVERY_SEARCH_TIMEOUT] [0x0] (recurse 0)
[11:00:24.015455] UpdateThread:636 Presence checking
[11:00:24.196064] MasterHandler:497 event: 6 [UPNP_DISCOVERY_SEARCH_RESULT] [0x0] (recurse 1)
[11:00:24.206762] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[11:00:24.484864] MasterHandler:497 event: 6 [UPNP_DISCOVERY_SEARCH_RESULT] [0x0] (recurse 0)
[11:00:24.515564] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[11:00:44.004762] MasterHandler:497 event: 7 [UPNP_DISCOVERY_SEARCH_TIMEOUT] [0x0] (recurse 0)
[11:00:44.004910] UpdateThread:636 Presence checking
[11:00:44.507185] MasterHandler:497 event: 6 [UPNP_DISCOVERY_SEARCH_RESULT] [0x0] (recurse 0)
[11:00:44.521300] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[11:00:44.627614] MasterHandler:497 event: 6 [UPNP_DISCOVERY_SEARCH_RESULT] [0x0] (recurse 0)
[11:00:44.640286] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[11:01:04.013237] MasterHandler:497 event: 7 [UPNP_DISCOVERY_SEARCH_TIMEOUT] [0x0] (recurse 0)
[11:01:04.013386] UpdateThread:636 Presence checking
[11:01:04.360073] MasterHandler:497 event: 6 [UPNP_DISCOVERY_SEARCH_RESULT] [0x0] (recurse 0)
[11:01:04.399635] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[11:01:04.558644] MasterHandler:497 event: 6 [UPNP_DISCOVERY_SEARCH_RESULT] [0x0] (recurse 0)
[11:01:04.571384] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[11:01:24.137245] MasterHandler:497 event: 7 [UPNP_DISCOVERY_SEARCH_TIMEOUT] [0x0] (recurse 0)
[11:01:24.137424] UpdateThread:636 Presence checking
[11:01:24.569365] MasterHandler:497 event: 6 [UPNP_DISCOVERY_SEARCH_RESULT] [0x0] (recurse 0)
[11:01:24.579968] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+
[11:01:25.016889] MasterHandler:497 event: 6 [UPNP_DISCOVERY_SEARCH_RESULT] [0x0] (recurse 0)
[11:01:25.027349] UpdateThread:693 [0x6a1aa0] UPnP keep alive: Cucina+


Around 11.00.24 Sonos disappeared from devices available to iOS. In my view the log is not showing anything particular, unless this is then an issue at iOS side.

Thanks for the great support, 

Best

Fabio

**Comment by philippe44** [comment]
Look here, it might be a similar problem https://github.com/philippe44/AirConnect/issues/62

**Comment by philippe44** [comment]
closed for inactivity
